platform:
- x64
environment:
  nodejs_version: "8"
  GITHUB_TOKEN:
    secure: arm8qFHbCiMkIOB3p6RO3+jKxggNcs7e1gk71ES8kK/olpCixntBXv6fDYCwoJ29
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
- node_modules
version: 0.0.{build}
branches:
  only:
  - master
  - /^v\d\.\d\.\d/
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm install
- npm update

test_script:
- node --version
- npm --version
- npm run lint
- if %APPVEYOR_REPO_TAG% EQU false npm run make

build_script:
- IF %APPVEYOR_REPO_TAG% EQU true npm run publish